name: pxe-boot-server

services:

  dnsmasq:
    image: dnsmasq
    build:
      context: dnsmasq
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./dnsmasq/tftp:/var/tftp
    restart: always

  # nfs:
  #   image: itsthenetwork/nfs-server-alpine
  #   restart: unless-stopped
  #   privileged: true
  #   environment:
  #     - SHARED_DIRECTORY=/nfs-export
  #   volumes:
  #     - ./nfs/export:/nfs-export
  #   ports:
  #     - 2049:2049

  nfs:
    image: erichough/nfs-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    # ports:
    #   - 2049:2049
    #   - 2049:2049/udp
    #   - 111:111
    #   - 111:111/udp
    #   - 32765:32765
    #   - 32765:32765/udp
    #   - 32767:32767
    #   - 32767:32767/udp
    network_mode: host
    environment:
      NFS_EXPORT_0: '/nfs-export *(rw,fsid=0,sync,no_subtree_check,no_root_squash)'
    volumes:
      - ./nfs/export:/nfs-export
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g


  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/var/www
