name: pxe-boot-server

services:

  dnsmasq:
    image: dnsmasq
    build:
      context: dnsmasq
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./dnsmasq/tftp:/var/tftp
    restart: always

  nfs:
    image: itsthenetwork/nfs-server-alpine
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfs-export
    volumes:
      - ./nfs/export:/nfs-export
    ports:
      - 2049:2049

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/var/www
