name: pxe-boot-server

services:

  dnsmasq:
    image: dnsmasq
    build:
      context: dnsmasq
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./dnsmasq/tftp:/var/tftp
    restart: always

  # nfs:
  #   image: itsthenetwork/nfs-server-alpine
  #   restart: unless-stopped
  #   privileged: true
  #   environment:
  #     - SHARED_DIRECTORY=/nfs-export
  #   volumes:
  #     - ./nfs/export:/nfs-export
  #   ports:
  #     - 2049:2049

  # nfs:
  #   image: erichough/nfs-server
  #   restart: unless-stopped
  #   cap_add:
  #     - SYS_ADMIN
  #   privileged: true
  #   ports:
  #     - 2049:2049
  #     - 2049:2049/udp
  #     - 111:111
  #     - 111:111/udp
  #     - 32765:32765
  #     - 32765:32765/udp
  #     - 32767:32767
  #     - 32767:32767/udp
  #   environment:
  #     NFS_EXPORT_0: '/nfs-export *(ro,fsid=0,sync,no_subtree_check,no_root_squash,insecure)'
  #   volumes:
  #     - ./nfs/export:/nfs-export
        
  # nfs:
  #   image: tangjiujun/nfs-server:v1.0
  #   restart: unless-stopped
  #   privileged: true
  #   ports:
  #     - 2049:2049
  #     - 2049:2049/udp
  #     - 111:111
  #     - 111:111/udp
  #     - 32765:32765
  #     - 32765:32765/udp
  #     - 32767:32767
  #     - 32767:32767/udp
  #   volumes:
  #     - ./nfs/export:/nfsshare

  nfs:
    image: nfs
    build:
      context: nfs
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./nfs/export:/nfsshare

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/var/www
